//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sporcu
{
    using System;
    using System.Collections.Generic;
    
    public partial class EgitmenlerBilgi
    {
        public int EgitmenNo { get; set; }
        public string EgitmenAdSoyad { get; set; }
        public string EgitmenAdres { get; set; }
        public string EgitmenTelefon { get; set; }
        public int SporcuNo { get; set; }
    }
}
