//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sporcu
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SporcuEntities : DbContext
    {
        public SporcuEntities()
            : base("name=SporcuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EgitmenlerBilgi> EgitmenlerBilgis { get; set; }
        public virtual DbSet<KullanicilarBilgi> KullanicilarBilgis { get; set; }
        public virtual DbSet<SalonlarBilgi> SalonlarBilgis { get; set; }
        public virtual DbSet<SporcularBilgi> SporcularBilgis { get; set; }
    
        public virtual int EgitmenEkle(string egitmenAdSoyad, string egitmenAdres, string egitmenTelefon, Nullable<int> sporcuNo)
        {
            var egitmenAdSoyadParameter = egitmenAdSoyad != null ?
                new ObjectParameter("EgitmenAdSoyad", egitmenAdSoyad) :
                new ObjectParameter("EgitmenAdSoyad", typeof(string));
    
            var egitmenAdresParameter = egitmenAdres != null ?
                new ObjectParameter("EgitmenAdres", egitmenAdres) :
                new ObjectParameter("EgitmenAdres", typeof(string));
    
            var egitmenTelefonParameter = egitmenTelefon != null ?
                new ObjectParameter("EgitmenTelefon", egitmenTelefon) :
                new ObjectParameter("EgitmenTelefon", typeof(string));
    
            var sporcuNoParameter = sporcuNo.HasValue ?
                new ObjectParameter("SporcuNo", sporcuNo) :
                new ObjectParameter("SporcuNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EgitmenEkle", egitmenAdSoyadParameter, egitmenAdresParameter, egitmenTelefonParameter, sporcuNoParameter);
        }
    
        public virtual ObjectResult<EgitmenListele_Result> EgitmenListele()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EgitmenListele_Result>("EgitmenListele");
        }
    
        public virtual int EgitmenSil(Nullable<int> egitmenNo)
        {
            var egitmenNoParameter = egitmenNo.HasValue ?
                new ObjectParameter("EgitmenNo", egitmenNo) :
                new ObjectParameter("EgitmenNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EgitmenSil", egitmenNoParameter);
        }
    
        public virtual int EgitmenYenile(Nullable<int> egitmenNo, string egitmenAdSoyad, string egitmenAdres, string egitmenTelefon, Nullable<int> sporcuNo)
        {
            var egitmenNoParameter = egitmenNo.HasValue ?
                new ObjectParameter("EgitmenNo", egitmenNo) :
                new ObjectParameter("EgitmenNo", typeof(int));
    
            var egitmenAdSoyadParameter = egitmenAdSoyad != null ?
                new ObjectParameter("EgitmenAdSoyad", egitmenAdSoyad) :
                new ObjectParameter("EgitmenAdSoyad", typeof(string));
    
            var egitmenAdresParameter = egitmenAdres != null ?
                new ObjectParameter("EgitmenAdres", egitmenAdres) :
                new ObjectParameter("EgitmenAdres", typeof(string));
    
            var egitmenTelefonParameter = egitmenTelefon != null ?
                new ObjectParameter("EgitmenTelefon", egitmenTelefon) :
                new ObjectParameter("EgitmenTelefon", typeof(string));
    
            var sporcuNoParameter = sporcuNo.HasValue ?
                new ObjectParameter("SporcuNo", sporcuNo) :
                new ObjectParameter("SporcuNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EgitmenYenile", egitmenNoParameter, egitmenAdSoyadParameter, egitmenAdresParameter, egitmenTelefonParameter, sporcuNoParameter);
        }
    
        public virtual int SalonEkle(string salonAdi, string salonm2, Nullable<int> egitmenNo)
        {
            var salonAdiParameter = salonAdi != null ?
                new ObjectParameter("SalonAdi", salonAdi) :
                new ObjectParameter("SalonAdi", typeof(string));
    
            var salonm2Parameter = salonm2 != null ?
                new ObjectParameter("Salonm2", salonm2) :
                new ObjectParameter("Salonm2", typeof(string));
    
            var egitmenNoParameter = egitmenNo.HasValue ?
                new ObjectParameter("EgitmenNo", egitmenNo) :
                new ObjectParameter("EgitmenNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SalonEkle", salonAdiParameter, salonm2Parameter, egitmenNoParameter);
        }
    
        public virtual ObjectResult<SalonListele_Result> SalonListele()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SalonListele_Result>("SalonListele");
        }
    
        public virtual int SalonSil(Nullable<int> salonNo)
        {
            var salonNoParameter = salonNo.HasValue ?
                new ObjectParameter("SalonNo", salonNo) :
                new ObjectParameter("SalonNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SalonSil", salonNoParameter);
        }
    
        public virtual int SalonYenile(Nullable<int> salonNo, string salonAdi, string salonm2, Nullable<int> egitmenNo)
        {
            var salonNoParameter = salonNo.HasValue ?
                new ObjectParameter("SalonNo", salonNo) :
                new ObjectParameter("SalonNo", typeof(int));
    
            var salonAdiParameter = salonAdi != null ?
                new ObjectParameter("SalonAdi", salonAdi) :
                new ObjectParameter("SalonAdi", typeof(string));
    
            var salonm2Parameter = salonm2 != null ?
                new ObjectParameter("Salonm2", salonm2) :
                new ObjectParameter("Salonm2", typeof(string));
    
            var egitmenNoParameter = egitmenNo.HasValue ?
                new ObjectParameter("EgitmenNo", egitmenNo) :
                new ObjectParameter("EgitmenNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SalonYenile", salonNoParameter, salonAdiParameter, salonm2Parameter, egitmenNoParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int SporcuEkle(string sporcuAdSoyad, string sporcuYas, string sporcuBoy, string sporcuKilo, string sporcuAdres, string sporcuTelefon)
        {
            var sporcuAdSoyadParameter = sporcuAdSoyad != null ?
                new ObjectParameter("SporcuAdSoyad", sporcuAdSoyad) :
                new ObjectParameter("SporcuAdSoyad", typeof(string));
    
            var sporcuYasParameter = sporcuYas != null ?
                new ObjectParameter("SporcuYas", sporcuYas) :
                new ObjectParameter("SporcuYas", typeof(string));
    
            var sporcuBoyParameter = sporcuBoy != null ?
                new ObjectParameter("SporcuBoy", sporcuBoy) :
                new ObjectParameter("SporcuBoy", typeof(string));
    
            var sporcuKiloParameter = sporcuKilo != null ?
                new ObjectParameter("SporcuKilo", sporcuKilo) :
                new ObjectParameter("SporcuKilo", typeof(string));
    
            var sporcuAdresParameter = sporcuAdres != null ?
                new ObjectParameter("SporcuAdres", sporcuAdres) :
                new ObjectParameter("SporcuAdres", typeof(string));
    
            var sporcuTelefonParameter = sporcuTelefon != null ?
                new ObjectParameter("SporcuTelefon", sporcuTelefon) :
                new ObjectParameter("SporcuTelefon", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SporcuEkle", sporcuAdSoyadParameter, sporcuYasParameter, sporcuBoyParameter, sporcuKiloParameter, sporcuAdresParameter, sporcuTelefonParameter);
        }
    
        public virtual ObjectResult<SporcuListele_Result> SporcuListele()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SporcuListele_Result>("SporcuListele");
        }
    
        public virtual int SporcuSil(Nullable<int> sporcuNo)
        {
            var sporcuNoParameter = sporcuNo.HasValue ?
                new ObjectParameter("SporcuNo", sporcuNo) :
                new ObjectParameter("SporcuNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SporcuSil", sporcuNoParameter);
        }
    
        public virtual int SporcuYenile(Nullable<int> sporcuNo, string sporcuAdSoyad, string sporcuYas, string sporcuBoy, string sporcuKilo, string sporcuAdres, string sporcuTelefon)
        {
            var sporcuNoParameter = sporcuNo.HasValue ?
                new ObjectParameter("SporcuNo", sporcuNo) :
                new ObjectParameter("SporcuNo", typeof(int));
    
            var sporcuAdSoyadParameter = sporcuAdSoyad != null ?
                new ObjectParameter("SporcuAdSoyad", sporcuAdSoyad) :
                new ObjectParameter("SporcuAdSoyad", typeof(string));
    
            var sporcuYasParameter = sporcuYas != null ?
                new ObjectParameter("SporcuYas", sporcuYas) :
                new ObjectParameter("SporcuYas", typeof(string));
    
            var sporcuBoyParameter = sporcuBoy != null ?
                new ObjectParameter("SporcuBoy", sporcuBoy) :
                new ObjectParameter("SporcuBoy", typeof(string));
    
            var sporcuKiloParameter = sporcuKilo != null ?
                new ObjectParameter("SporcuKilo", sporcuKilo) :
                new ObjectParameter("SporcuKilo", typeof(string));
    
            var sporcuAdresParameter = sporcuAdres != null ?
                new ObjectParameter("SporcuAdres", sporcuAdres) :
                new ObjectParameter("SporcuAdres", typeof(string));
    
            var sporcuTelefonParameter = sporcuTelefon != null ?
                new ObjectParameter("SporcuTelefon", sporcuTelefon) :
                new ObjectParameter("SporcuTelefon", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SporcuYenile", sporcuNoParameter, sporcuAdSoyadParameter, sporcuYasParameter, sporcuBoyParameter, sporcuKiloParameter, sporcuAdresParameter, sporcuTelefonParameter);
        }
    }
}
