//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sporcu
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalonlarBilgi
    {
        public int SalonNo { get; set; }
        public string SalonAdi { get; set; }
        public string Salonm2 { get; set; }
        public int EgitmenNo { get; set; }
    }
}
