//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sporcu
{
    using System;
    using System.Collections.Generic;
    
    public partial class SporcularBilgi
    {
        public int SporcuNo { get; set; }
        public string SporcuAdSoyad { get; set; }
        public string SporcuYas { get; set; }
        public string SporcuBoy { get; set; }
        public string SporcuKilo { get; set; }
        public string SporcuAdres { get; set; }
        public string SporcuTelefon { get; set; }
    }
}
